language: java

jdk:
 - openjdk8
 - oraclejdk8

before_script: cd seip2019/

script:
 - mvn clean package jacoco:report cobertura:cobertura

after_success:
  - bash <(curl -s https://codecov.io/bash) -t 8a5a32f2-5073-4954-8a80-d0b320ea1c69
